### ISSUE TITLE
a09 fails now on 6909 code "LDA   A,X"

### ISSUE THREAD

**Issue by dieterdeyke** [Arakula/A09#11]
LDA   A,X should load accumulator A with the value found at the memory address calculated by adding the old value of accumulator A and the X index register. The error message is:

cputest.asm(1448) : error 3: Undefined label in "       LDA   A,X"
cputest.asm(1448) : warning 4: Ambiguous 6800 alternate notation in "       LDA   A,X"

This used to work OK before.

**Comment by Arakula** [comment]
Mhm ... seems to be an unfortunate side effect of what I did to resolve issue #10
I'll look into it.

**Comment by Arakula** [comment]
OK, that should be fixed now.

**Comment by Arakula** [comment]
... and this time I did more extensive regression tests before uploading it ... oh well.

**Comment by dieterdeyke** [comment]
Hermann Seib ***@***.***> writes:

> OK, that should be fixed now.

Thank you, everything I tested works OK again.
-- 
Dieter Deyke
***@***.***
Get my Gnupg key:
gpg --keyserver keys.gnupg.net --recv-keys B116EA20
