### ISSUE TITLE
Last commit breaks FILCHR

### ISSUE THREAD

**Issue by AR1972** [Arakula/A09#13]
I'm using "FILCHR TEXT $3F" in my project, last commit always uses 0x00 as the FILCHR
adding this hack to settext() returns previous behavior.

if (memcmp(namebuf, "FILCHR", 6) != 0) {
	/* to keep texts separate from the normal labels' way, prepend them with & */
	if (*namebuf != '&')
	{
		sprintf(iname, "&%.*s", (int)(sizeof(iname) - 2), namebuf);
		namebuf = iname;
	}
}

**Comment by mickecamino** [comment]
I can confirm this. I spent about one hour trying to compile my code with fill character $FF, nothing worked. 
After patching with the above code it works if I enter "FILCHR TEXT $FF" in the the code I try to compile.
It will however not work if I try to add -dFILCHR=$FF to the command line

**Comment by Arakula** [comment]
OK, I got some time now to look at it.
You're right, the last commit introduced a problem here.
I won't include your solution above, however; the better solution (both for space and execution time) is to change
`if (!strcmp(namebuf, "FILCHR"))        /* special for FILCHR : set internal */`
(some lines down from your fix) to
`if (!strcmp(namebuf, "&FILCHR"))        /* special for FILCHR : set internal */`
... that's what the next version (due maybe today, maybe tomorrow) will contain. It will create a little clash with your solution, however, so watch out.

**Comment by Arakula** [comment]
Oh, wait a moment ... that's what your pull request does anyway. So, no clash, all good :grin:

**Comment by Arakula** [comment]
OK, that should be fixed.
