### ISSUE TITLE
PSH B, PSH A, PUL A, PUL B not valid 6800 instructions although LDA A, CMP A etc all are handled the same as LDAA, CMPA

### ISSUE THREAD

**Issue by stanleyruppert** [Arakula/A09#18]
When assembling (using -oM00 option) some 6800 code in old Motorola format, LDA A treated same as LDAA etc for all instructions but PSH and PUL.  
I've needed to manually convert PSH A to PSHA etc in the source files. Could PSH and PUL be handled as well for the 6800 option?

**Comment by Arakula** [comment]
I added that in V1.61, for the 6800/6801/68HC11 assemblers.

**Comment by stanleyruppert** [comment]
Terrific! Many thanks! Greatly appreciate your work on the assembler and disassembler. Both have been super helpful.
